# Generated by Django 4.2.3 on 2023-07-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='link',
            field=models.URLField(default='google.com', max_length=2000),
            preserve_default=False,
        ),
    ]
