# Generated by Django 4.2.3 on 2023-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_alter_bookmark_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='link',
            field=models.URLField(error_messages={'invalid': 'Enter a valid URL. e.g https://google.com'}, max_length=2000),
        ),
    ]
